version: '3.8'

services:
  homepage-editor:
    build: .
    container_name: homepage-editor
    image: homepage-editor:latest
    ports:
      - "8089:5000"
    volumes:
      - /mnt/nfs/swarm/dockervolumes/homepage/services.yaml:/data/settings.yaml
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - YAML_FILE=/data/settings.yaml
    restart: unless-stopped
